sudo: true

script:
  - docker build -t $PLUGIN_NAME:$(git describe --always) .
  - mkdir -p ./plugin/rootfs
  - docker create --name dvp-minfs $PLUGIN_NAME:$(git describe --always)
  - docker export dvp-minfs | tar -x -C ./plugin/rootfs
  - mv ./plugin/rootfs/tmp/config.json ./plugin
  - docker plugin create $PLUGIN_NAME:$(git describe --always) ./plugin
  - docker plugin ls
