sudo: true

install:
  - curl -sSL https://get.docker.com/ | sh

script:
  - docker build -t $PLUGIN_NAME .
  - mkdir -p ./plugin/rootfs
  - docker create --name plugin-rootfs $PLUGIN_NAME
  - docker export plugin-rootfs | tar -x -C ./plugin/rootfs
  - mv ./plugin/rootfs/tmp/config.json ./plugin
  - docker plugin create $PLUGIN_NAME ./plugin

after_success:
  - if [ "$TRAVIS_BRANCH" == "master" ]; then
    docker login -u="$DOCKER_USERNAME" -p="$DOCKER_PASSWORD";
    docker plugin push $(PLUGIN_NAME);
    fi

